# Generated by Django 5.1.2 on 2025-03-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tipo_residuo', models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('plastico', 'Plástico'), ('vidro', 'Vidro'), ('metal', 'Metal'), ('organico', 'Orgânico')], max_length=100)),
            ],
        ),
    ]
